import type { AppState } from '../types/models';

const now = new Date().toISOString();

export const seedState: AppState = {
  currentProjectId: 'project_demo',
  projects: [
    {
      id: 'project_demo',
      name: 'Vila Olímpia',
      code: 'DMX-GMB',
      address: 'São Paulo - SP',
      status: 'ativo',
      createdAt: now,
    },
  ],
  disciplines: [
    { id: 'disc_arq', code: 'ARQ', name: 'Arquitetura', color: '#10b981' },
    { id: 'disc_est', code: 'EST', name: 'Estrutura', color: '#3b82f6' },
    { id: 'disc_ele', code: 'ELE', name: 'Elétrica', color: '#f59e0b' },
    { id: 'disc_hid', code: 'HID', name: 'Hidráulica', color: '#06b6d4' },
    { id: 'disc_inc', code: 'INC', name: 'Incêndio', color: '#ef4444' },
    { id: 'disc_int', code: 'INT', name: 'Interiores', color: '#22c55e' },
    { id: 'disc_top', code: 'TOP', name: 'Topografia', color: '#8b5cf6' },
  ],
  milestones: [
    {
      id: 'milestone_1',
      projectId: 'project_demo',
      title: 'Projeto executivo - Arquitetura pavimento tipo',
      disciplineCode: 'ARQ',
      requiredForConstructionDate: '2026-07-10',
      promisedByDesignerDate: '2026-07-05',
      responsibleCompany: 'Projetista externo',
      status: 'no_prazo',
    },
    {
      id: 'milestone_2',
      projectId: 'project_demo',
      title: 'Compatibilização estrutura x instalações',
      disciplineCode: 'EST',
      requiredForConstructionDate: '2026-07-18',
      promisedByDesignerDate: '2026-07-20',
      responsibleCompany: 'Coordenação',
      status: 'risco',
    },
  ],
  documents: [
    {
      id: 'doc_demo_1',
      projectId: 'project_demo',
      code: 'DMX-GMB-EX-ARQ-P03-PLA-002',
      title: 'Planta de acabamentos - Apto 31',
      disciplineCode: 'ARQ',
      phase: 'executivo',
      floor: '03',
      area: 'Apto 31',
      currentRevisionId: 'rev_demo_2',
      latestApprovedRevisionId: 'rev_demo_2',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'doc_demo_2',
      projectId: 'project_demo',
      code: 'DMX-GMB-EX-ELE-P03-PLA-001',
      title: 'Planta elétrica - Apto 31',
      disciplineCode: 'ELE',
      phase: 'executivo',
      floor: '03',
      area: 'Apto 31',
      currentRevisionId: 'rev_demo_3',
      createdAt: now,
      updatedAt: now,
    },
  ],
  revisions: [
    {
      id: 'rev_demo_1',
      documentId: 'doc_demo_1',
      revisionCode: 'R04',
      fileName: 'DMX-GMB-EX-ARQ-P03-PLA-002-R04.pdf',
      fileUrl: '',
      uploadedBy: 'Coordenador',
      uploadedAt: now,
      status: 'obsoleto',
    },
    {
      id: 'rev_demo_2',
      documentId: 'doc_demo_1',
      revisionCode: 'R05',
      fileName: 'DMX-GMB-EX-ARQ-P03-PLA-002-R05.pdf',
      fileUrl: '',
      uploadedBy: 'Coordenador',
      uploadedAt: now,
      status: 'liberado_obra',
      approvedAt: now,
      approvedBy: 'Coordenador',
      releasedForSiteAt: now,
    },
    {
      id: 'rev_demo_3',
      documentId: 'doc_demo_2',
      revisionCode: 'R02',
      fileName: 'DMX-GMB-EX-ELE-P03-PLA-001-R02.pdf',
      fileUrl: '',
      uploadedBy: 'Projetista',
      uploadedAt: now,
      status: 'em_revisao',
    },
  ],
  issues: [
    {
      id: 'issue_demo_1',
      projectId: 'project_demo',
      documentId: 'doc_demo_2',
      revisionId: 'rev_demo_3',
      pageNumber: 1,
      x: 42,
      y: 56,
      category: 'Incompatibilidade',
      severity: 'alta',
      title: 'Conferir interferência com shaft',
      description: 'Ponto elétrico próximo ao shaft precisa ser revisado antes da liberação para obra.',
      assignedTo: 'Projetista elétrico',
      status: 'aberta',
      createdBy: 'Coordenador',
      createdAt: now,
    },
  ],
  printRequests: [],
};
